#import "AppDelegate.h"

static NSString * const GNExternalDocumentDir = @"/var/mobile/Documents/GarminNativeSender";
static NSString * const GNInputPrgPath = @"/var/mobile/Documents/GarminNativeSender/input.prg";

@interface AppDelegate ()
@property (nonatomic, strong) GNSender *sender;
@property (nonatomic, strong) UITextView *logView;
@property (nonatomic, strong) UIProgressView *progressView;
@property (nonatomic, strong) UILabel *statusLabel;
@property (nonatomic, strong) UIButton *scanButton;
@property (nonatomic, strong) UIButton *connectButton;
@property (nonatomic, strong) UIButton *uploadButton;
@property (nonatomic, strong) UIButton *exportButton;
@property (nonatomic, strong) UIButton *stopButton;
@end

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
    (void)application;
    (void)launchOptions;

    [[NSFileManager defaultManager] createDirectoryAtPath:GNExternalDocumentDir
                              withIntermediateDirectories:YES
                                               attributes:nil
                                                    error:nil];

    self.sender = [[GNSender alloc] init];
    self.sender.delegate = self;
    self.sender.gfdiPacketSize = 3072;
    self.sender.bleFragmentSize = 20;
    self.sender.pipelineWindow = 8;
    self.sender.reliableMlr = YES;

    UIViewController *root = [[UIViewController alloc] init];
    root.view.backgroundColor = [UIColor colorWithWhite:0.96 alpha:1.0];
    self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
    self.window.rootViewController = root;
    [self.window makeKeyAndVisible];

    CGFloat width = CGRectGetWidth(root.view.bounds);
    CGFloat y = 28.0;
    UILabel *title = [[UILabel alloc] initWithFrame:CGRectMake(12, y, width - 24, 28)];
    title.text = @"Garmin Native Sender";
    title.font = [UIFont boldSystemFontOfSize:22];
    [root.view addSubview:title];
    y += 36;

    UILabel *path = [[UILabel alloc] initWithFrame:CGRectMake(12, y, width - 24, 44)];
    path.text = [NSString stringWithFormat:@"PRG: %@", GNInputPrgPath];
    path.font = [UIFont systemFontOfSize:12];
    path.numberOfLines = 2;
    [root.view addSubview:path];
    y += 52;

    self.statusLabel = [[UILabel alloc] initWithFrame:CGRectMake(12, y, width - 24, 40)];
    self.statusLabel.text = @"Idle. Copy a PRG to the path above, then scan.";
    self.statusLabel.font = [UIFont systemFontOfSize:14];
    self.statusLabel.numberOfLines = 2;
    [root.view addSubview:self.statusLabel];
    y += 46;

    self.progressView = [[UIProgressView alloc] initWithFrame:CGRectMake(12, y, width - 24, 8)];
    [root.view addSubview:self.progressView];
    y += 20;

    self.scanButton = [self buttonWithTitle:@"Scan Garmin" action:@selector(scanTapped:)];
    self.connectButton = [self buttonWithTitle:@"Connect First" action:@selector(connectTapped:)];
    self.uploadButton = [self buttonWithTitle:@"Upload PRG" action:@selector(uploadTapped:)];
    self.exportButton = [self buttonWithTitle:@"Export Trace" action:@selector(exportTapped:)];
    self.stopButton = [self buttonWithTitle:@"Stop" action:@selector(stopTapped:)];

    NSArray *buttons = @[self.scanButton, self.connectButton, self.uploadButton, self.exportButton, self.stopButton];
    CGFloat buttonWidth = (width - 36) / 2.0;
    for (NSUInteger i = 0; i < buttons.count; i++) {
        UIButton *button = buttons[i];
        CGFloat x = 12 + (i % 2) * (buttonWidth + 12);
        CGFloat rowY = y + (i / 2) * 46;
        button.frame = CGRectMake(x, rowY, buttonWidth, 38);
        [root.view addSubview:button];
    }
    y += 3 * 46 + 6;

    self.logView = [[UITextView alloc] initWithFrame:CGRectMake(12, y, width - 24, CGRectGetHeight(root.view.bounds) - y - 12)];
    self.logView.autoresizingMask = UIViewAutoresizingFlexibleWidth | UIViewAutoresizingFlexibleHeight;
    self.logView.editable = NO;
    self.logView.font = [UIFont fontWithName:@"Menlo" size:11] ?: [UIFont systemFontOfSize:11];
    self.logView.backgroundColor = [UIColor colorWithWhite:0.08 alpha:1.0];
    self.logView.textColor = [UIColor colorWithWhite:0.92 alpha:1.0];
    self.logView.layer.cornerRadius = 6.0;
    [root.view addSubview:self.logView];

    [self appendLog:@"Native sender booted. App-level BLE/Garmin packet trace is on."];
    [self appendLog:@"This sniffs traffic generated by this app; raw HCI sniffing still needs the BTServer/BTPacketLogger experiment."];
    return YES;
}

- (UIButton *)buttonWithTitle:(NSString *)title action:(SEL)action {
    UIButton *button = [UIButton buttonWithType:UIButtonTypeSystem];
    [button setTitle:title forState:UIControlStateNormal];
    button.titleLabel.font = [UIFont boldSystemFontOfSize:15];
    button.backgroundColor = [UIColor whiteColor];
    button.layer.borderWidth = 1.0;
    button.layer.borderColor = [UIColor colorWithRed:0.20 green:0.42 blue:0.52 alpha:1.0].CGColor;
    button.layer.cornerRadius = 5.0;
    [button addTarget:self action:action forControlEvents:UIControlEventTouchUpInside];
    return button;
}

- (void)scanTapped:(id)sender {
    (void)sender;
    [self.sender startScan];
}

- (void)connectTapped:(id)sender {
    (void)sender;
    [self.sender connectFirstDiscoveredPeripheral];
}

- (void)uploadTapped:(id)sender {
    (void)sender;
    [self.sender uploadPRGAtPath:GNInputPrgPath];
}

- (void)exportTapped:(id)sender {
    (void)sender;
    NSString *path = [self.sender exportTrace];
    if (path.length) {
        [self appendLog:[NSString stringWithFormat:@"Trace exported: %@", path]];
    }
}

- (void)stopTapped:(id)sender {
    (void)sender;
    [self.sender stop];
}

- (void)senderDidLog:(NSString *)message {
    [self appendLog:message];
}

- (void)senderDidUpdateStatus:(NSString *)status {
    dispatch_async(dispatch_get_main_queue(), ^{
        self.statusLabel.text = status;
    });
}

- (void)senderDidUpdateProgressOffset:(NSUInteger)offset total:(NSUInteger)total {
    dispatch_async(dispatch_get_main_queue(), ^{
        float value = total ? (float)offset / (float)total : 0.0f;
        self.progressView.progress = value;
        self.statusLabel.text = [NSString stringWithFormat:@"Uploaded %lu / %lu bytes (%.1f%%)",
                                 (unsigned long)offset,
                                 (unsigned long)total,
                                 value * 100.0f];
    });
}

- (void)appendLog:(NSString *)message {
    dispatch_async(dispatch_get_main_queue(), ^{
        NSDateFormatter *formatter = [[NSDateFormatter alloc] init];
        formatter.dateFormat = @"HH:mm:ss.SSS";
        NSString *line = [NSString stringWithFormat:@"%@  %@\n", [formatter stringFromDate:[NSDate date]], message];
        self.logView.text = [self.logView.text ?: @"" stringByAppendingString:line];
        NSRange bottom = NSMakeRange(MAX((NSInteger)self.logView.text.length - 1, 0), 1);
        [self.logView scrollRangeToVisible:bottom];
    });
}

@end
